### PR TITLE
Fixes after review

### PR DESCRIPTION
**Pull request by pietrushnic**

### CODE REVIEW

**Comment by pietrushnic** [comment]
@miczyg1 despite above changes I still cannot boot Debian from NFS:

```
[  OK  ] Started Update UTMP about System Boot/Shutdown.
[    **] A start job is running for LSB: Raise network interf...10s / no limit)[   17.551433] nfs: server 192.168.0.106 not responding, still trying
[*     ] A start job is running for LSB: Raise network interf...13s / no limit)[   20.224750] random: crng init done
[    **] A start job is running for LSB: Raise network interf...30s / no limit)
```

**Comment by pietrushnic** [comment]
@miczyg1 the problem appears to be retrieving DHCP for eth0. After removing eth0 from `/etc/interfaces` things started to work correctly. Second thing is no login/pass mentioned in documentation. Third we should introduce rootfs versioning if we want to use thing in long term.

**Comment by pietrushnic** [comment]
@miczyg1 

```
apu@pcengines:~$ sudo apt-get update
sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set
apu@pcengines:~$ dmidecode -t bios
# dmidecode 2.12
/dev/mem: Permission denied
```

**Comment by pietrushnic** [comment]
@miczyg1 I tried to change password, so I did chown. How strange this can be:

```
root@silvertine:/# passwd                                                                                              
Enter new UNIX password:                                                                                               
Retype new UNIX password:                                                                                                                                                                                                                     
passwd: System error                                                                                                   
passwd: password unchanged   
```

It happen that all files have `apu:apu` ownership, what cause `passwd`, `sudo`, `su` and friends go mad. Man you added a lot of headache with this implementation.

**Comment by miczyg1** [comment]
@pietrushnic  I can confirm only the issues with password and ownership. I have not encountered such problems with network interfaces.

The ownerships somehow changed after compressing the rootfs even though I used -p flag with tar so it should keep  original permissions. Anyway I am aware of that and will try to fix this, or reproduce and find a solution.

About root credentials, I forgot. Will add it of course.

**Comment by pietrushnic** [comment]
@miczyg1 it looks like this PR is no longer valid, am I correct ? If yes please close it

**Comment by miczyg1** [comment]
Yes, Your are right. But I do not have privileges to close this PR. You would have to do it by yourself @pietrushnic

**Pull request closed without merging**
